### ISSUE TITLE
I am running main.py on mac and getting below error.

### ISSUE THREAD

**Issue by milind1248** [akmadan/Emotion_Detection_CNN#1]
I am running main.py on mac and getting below error.

/Users/Name/PycharmProjects/MyProject/venv/bin/python /Users/Name/PycharmProjects/MyProject/Emotion_Detection_CNN-main/main.py
1.face_classifier= <CascadeClassifier 0x7ff35297ee50>
Traceback (most recent call last):
  File "/Users/Name/PycharmProjects/MyProject/Emotion_Detection_CNN-main/main.py", line 25, in <module>
    classifier = load_model('model.h5')
  File "/Users/Name/PycharmProjects/MyProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 184, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/Users/Name/PycharmProjects/MyProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 177, in load_model_from_hdf5
    model = model_config_lib.model_from_config(model_config,
  File "/Users/Name/PycharmProjects/MyProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/Users/Name/PycharmProjects/MyProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 105, in deserialize
    return deserialize_keras_object(
  File "/Users/Name/PycharmProjects/MyProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 369, in deserialize_keras_object
    return cls.from_config(
  File "/Users/Name/PycharmProjects/MyProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 397, in from_config
    layer = layer_module.deserialize(layer_config,
  File "/Users/Name/PycharmProjects/MyProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 105, in deserialize
    return deserialize_keras_object(
  File "/Users/Name/PycharmProjects/MyProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 375, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/Users/Name/PycharmProjects/MyProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 655, in from_config
    return cls(**config)
  File "/Users/Name/PycharmProjects/MyProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/layers/convolutional.py", line 592, in __init__
    kernel_initializer=initializers.get(kernel_initializer),
  File "/Users/Name/PycharmProjects/MyProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/initializers.py", line 194, in get
    return deserialize(identifier)
  File "/Users/Name/PycharmProjects/MyProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/initializers.py", line 182, in deserialize
    return deserialize_keras_object(
  File "/Users/Name/PycharmProjects/MyProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 361, in deserialize_keras_object
    (cls, cls_config) = class_and_config_for_serialized_keras_object(
  File "/Users/Name/PycharmProjects/MyProject/venv/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 321, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
**ValueError: Unknown initializer: HeNormal**

Process finished with exit code 1

**Comment by mafdymagdy** [comment]
Same here

**Comment by akmadan** [comment]
Did you try this solution? - https://stackoverflow.com/questions/63596569/valueerror-unknown-initializer-henormal

**Comment by milind1248** [comment]
Hi All,

I can able run existing program (main.py) using below upgrade command tensorflow & keras. I have not added any extra code.

@akmadan, solution you provided in above link even not required as after upgrade your (existing) code is working fine now.
Thank you for all your help. you Rock

pip install --upgrade tensorflow
pip install --upgrade keras

**Comment by milind1248** [comment]
Could you please add confusion matrix at end while creating h5 model?

Regards,
Milind Talele
